### ISSUE TITLE
undefined reference to `__imp_WSAGetLastError' collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by sivakumarmallipeddi** [aviumtechnologies/pixhawk-sil-connector#1]
I add the extension and ran the make file but i get the following error 

make
Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0xd4a):
undefined reference to `__imp_WSAStartup'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0xfc4):
undefined reference to `__imp_WSACleanup'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0xfe6):
undefined reference to `__imp_WSACleanup'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x355b):
undefined reference to `__imp_WSASetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3586):
undefined reference to `__imp_WSAStringToAddressA'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x359c):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x35f6):
undefined reference to `__imp_htons'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x37ea):
undefined reference to `__imp_WSASocketW'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3975):
undefined reference to `__imp_setsockopt'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x39b0):
undefined reference to `__imp_bind'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x39d8):
undefined reference to `__imp_listen'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3a57):
undefined reference to `__imp_select'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3a78):
undefined reference to `__imp_accept'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3bb1):
undefined reference to `__imp_htons'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3bbd):
undefined reference to `__imp_ntohl'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x3bc5):
undefined reference to `__imp_htonl'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x41e5):
undefined reference to `__imp_setsockopt'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x4270):
undefined reference to `__imp_WSACleanup'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x429b):
undefined reference to `__imp_WSAStartup'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x517e):
undefined reference to `__imp_ioctlsocket'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0x52aa):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x41):
undefined reference to `__imp_closesocket'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x78):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0xbf):
undefined reference to `__imp_ioctlsocket'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x11f):
undefined reference to `__imp_setsockopt'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x132):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops9poll_readEyhiRSt10error_code[_ZN4asio6detail10socket_ops9poll_readEyhiRSt10error_code]+0x7d):
undefined reference to `__imp_select'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops9poll_readEyhiRSt10error_code[_ZN4asio6detail10socket_ops9poll_readEyhiRSt10error_code]+0xcf):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops10poll_writeEyhiRSt10error_code[_ZN4asio6detail10socket_ops10poll_writeEyhiRSt10error_code]+0x7c):
undefined reference to `__imp_select'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops10poll_writeEyhiRSt10error_code[_ZN4asio6detail10socket_ops10poll_writeEyhiRSt10error_code]+0xce):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb[_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb]+0x2a4):
undefined reference to `__imp_WSASend'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb[_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb]+0x2af):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3tcpEE8shutdownEv]+0x3b8):
undefined reference to `__imp_WSASend'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3tcpEE8shutdownEv]+0x3cd):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail21write_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code[_ZN4asio6detail21write_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code]+0x5b):
undefined reference to `__imp_WSASend'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail21write_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code[_ZN4asio6detail21write_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code]+0x6a):
undefined reference to `__imp_WSAGetLastError'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail20read_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code[_ZN4asio6detail20read_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code]+0x108):
undefined reference to `__imp_WSARecv'
C:\Users\SIVAKU~1\AppData\Local\Temp\mex_12248308171980_8096\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text$_ZN4asio6detail20read_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code[_ZN4asio6detail20read_buffer_sequenceINS_19basic_stream_socketINS_2ip3tcpENS_15any_io_executorEEENS_17mutable_buffers_1EPKNS_14mutable_bufferENS0_14transfer_all_tEEEyRT_RKT0_RKT1_T2_RSt10error_code]+0x120):
undefined reference to `__imp_WSAGetLastError'
collect2.exe: error: ld returned 1 exit status

Error in make (line 4)
mex -I./includes pixhawk_sil_connector.cpp

I understand that it is related to lib file. I found the file and add it to the matlab path but i still get the same error. What should i be doing or where am I going wrong? Thank you in advance.

**Comment by aviumtechnologies** [comment]
Hi! I was able to reproduce the error in MATLAB R2022a with MinGW64:

`Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\boych\AppData\Local\Temp\mex_255197456074141_5376\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0xd0a): undefined reference to `__imp_WSAStartup'
C:\Users\boych\AppData\Local\Temp\mex_255197456074141_5376\pixhawk_sil_connector.obj:pixhawk_sil_connector.cpp:(.text+0xf84): undefined reference to `__imp_WSACleanup'`
...
`undefined reference to `__imp_WSAGetLastError'
collect2.exe: error: ld returned 1 exit status


Error in make (line 4)
mex -I./includes pixhawk_sil_connector.cpp`


You need to add the following flag to the make.m file - `-lws2_32`. Please try to compile with the following command - `mex -I./includes pixhawk_sil_connector.cpp -lws2_32`. 

A new version of the SITL Pixhawk connector will be coming out soon. It will contain a more realistic GPS sensor (including noise). I will make sure to update the documentation regrading compiling with MinGW64.
