### ISSUE TITLE
Sensors not detected by PX-Autopilot SITL (54d8257) as they don't have explicit ids

### ISSUE THREAD

**Issue by KBoychev** [aviumtechnologies/pixhawk-sil-connector#3]
Issue observed with PX-Autopilot commit 54d825730ea81ff63532552f562a9b63aa66237b

**Comment by aviumtechnologies** [comment]
Fixed in release 1.3.0 [https://github.com/aviumtechnologies/pixhawk-sil-connector/releases/tag/1.3.0](https://github.com/aviumtechnologies/pixhawk-sil-connector/releases/tag/1.3.0).
