### ISSUE TITLE
Windows Firewall and WSL

### ISSUE THREAD

**Issue by teklot** [aviumtechnologies/pixhawk-sil-connector#5]
Hi Everyone,
This seems a Windows/WSL issue, but I was not able to find an answer online. Created Windows Firewall rules to allow inbound and outbound traffic but did not work. However, when the Windows Firewall (public profile) is disabled, everything works as described and expected. I checked possible conflicting rules but did not find any. Can you please help to resolve this issue? I am using Windows 10 and WSL2.

Thank you for the work you have done!

**Comment by embentionsupport-dronamics** [comment]
Hi! Thank you for reaching out. So far I haven't had issues with the connector even when the firewall was enabled. The issue might be specific to your Windows/WSL setup. Unfortunately I am no expert in firewalls or rules, nevertheless I will check what my settings are an I will let you know. As far as I remember I never had to change any firewall settings or rules for the connector to work.

**Comment by teklot** [comment]
This caused by a Windows Firewall rule set for MATLAB, blocking all incoming traffic on all ports.
